# show and hide styled inputs, update natural language statement
$('.input-container').click ->
  target = $(this)
  targetInput = $(this).find('input')
  targetSelect = $(this).find('select')
  styledSelect = $(this).find('.newSelect')
  target.addClass 'active'
  targetInput.focus()
  targetInput.change ->
    inputValue = $(this).val()
    placeholder = target.find('.placeholder')
    target.removeClass 'active'
    placeholder.html inputValue
    return
  targetSelect.change ->
    inputValue = $(this).val()
    placeholder = target.find('.placeholder')
    target.removeClass 'active'
    placeholder.html inputValue
    return
  styledSelect.click ->
    `var target`
    target = $(this)
    setTimeout (->
      target.parent().parent().removeClass 'active'
      return
    ), 10
    return
  return
# style selects
# Create the new select
select = $('.fancy-select')
select.wrap '<div class="newSelect"></div>'
$('.newSelect').prepend '<div class="newOptions"></div>'
#populate the new select
select.each ->
  selectOption = $(this).find('option')
  target = $(this).parent().find('.newOptions')
  selectOption.each ->
    optionContents = $(this).html()
    optionValue = $(this).attr('value')
    target.append '<div class="newOption" data-value="' + optionValue + '">' + optionContents + '</div>'
    return
  return
# new select functionality
newSelect = $('.newSelect')
newOption = $('.newOption')
# update based on selection 
newOption.on 'mouseup', ->
  OptionInUse = $(this)
  siblingOptions = $(this).parent().find('.newOption')
  newValue = $(this).attr('data-value')
  selectOption = $(this).parent().parent().find('select option')
  # style selected option
  siblingOptions.removeClass 'selected'
  OptionInUse.addClass 'selected'
  # update the actual input
  selectOption.each ->
    optionValue = $(this).attr('value')
    if newValue == optionValue
      $(this).prop 'selected', true
    else
      $(this).prop 'selected', false
    return
  return
newSelect.click ->
  target = $(this)
  target.parent().find('select').change()
  return

# ---
# generated by js2coffee 2.2.0
